# Generated by Django 4.2.7 on 2023-11-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='bairro',
            field=models.CharField(default='', max_length=255),
        ),
    ]
