# Generated by Django 4.2.7 on 2023-11-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_local_bairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='bairro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
