# Generated by Django 4.2.7 on 2023-11-13 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_local_bairro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='local',
            new_name='locais',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='opcao',
            new_name='produtos',
        ),
    ]
